# Generated by Django 6.0.1 on 2026-01-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('spend_type', models.CharField(choices=[('NEEDS', 'Needs'), ('WANTS', 'Wants'), ('SAVINGS', 'Savings'), ('DEBTS', 'Debts'), ('INVESTMENTS', 'Investments')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('income_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('needs_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wants_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debts_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investments_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
